# WARNING: DO NOT EDIT THIS FILE DIRECTLY
# This file may be modified with future updates, changing it would break it
# You should copy the production.example.py file as "production.py" and place your settings there
# That file will not be tracked by git

from pathlib import Path
import os
from urllib.parse import urlparse

import dj_database_url

from ballsdex.settings import read_settings, settings

try:
    read_settings(Path("../config.toml"))
except FileNotFoundError:
    from rich import print

    print(
        "[yellow][bold]Could not find ../config.toml file.[/bold] "
        "Please run the bot once to generate this file.[/yellow]"
    )

BASE_DIR = Path(__file__).resolve().parent.parent


# Read Django secret key from environment if provided (recommended in production)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or None

# WARNING: DO NOT ADD EXTERNAL HOSTS HERE!!
# If you want to expose your admin panel online, please follow this tutorial:
# https://github.com/Ballsdex-Team/BallsDex-DiscordBot/wiki/Serving-the-admin-panel-online
# THIS HAS SECURITY IMPLICATIONS, ENABLES PRIVILEGE ESCALATION AND REMOTE CODE EXECUTION

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]
# Extend allowed hosts from config.toml (admin-panel.url) and env var DJANGO_ALLOWED_HOSTS
_extra_hosts: list[str] = []
if settings.admin_url:
    try:
        _parsed = urlparse(settings.admin_url)
        if _parsed.hostname:
            _extra_hosts.append(_parsed.hostname)
    except Exception:
        pass
env_hosts = os.getenv("DJANGO_ALLOWED_HOSTS")
if env_hosts:
    _extra_hosts.extend([h.strip() for h in env_hosts.split(",") if h.strip()])
if _extra_hosts:
    # keep order but de-duplicate
    for _h in _extra_hosts:
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)
INTERNAL_IPS = [
    "127.0.0.1",
]

# CSRF trusted origins for reverse proxies and HTTPS
CSRF_TRUSTED_ORIGINS = []
for _h in ALLOWED_HOSTS:
    if ":" in _h:
        # likely an IPv6 or host:port; Django expects scheme+host without port
        host_only = _h.split(":")[0]
    else:
        host_only = _h
    if host_only:
        CSRF_TRUSTED_ORIGINS.append(f"https://{host_only}")
        CSRF_TRUSTED_ORIGINS.append(f"http://{host_only}")


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "admin_auto_filters",
    "django_admin_action_forms",
    "django_admin_inline_paginator",
    "social_django",
    "admin_panel.apps.BallsdexAdminConfig",
    "bd_models",
    "preview",
]

MIDDLEWARE = [
    "allow_cidr.middleware.AllowCIDRMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "admin_panel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "admin_panel.wsgi.application"

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        },
        "uvicorn": {
            "()": "uvicorn.logging.ColourizedFormatter",
            "format": "{levelprefix} ({name}) {msg}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "uvicorn",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
    },
    "loggers": {
        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {"default": dj_database_url.config("BALLSDEXBOT_DB_URL")}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static"
STATICFILES_DIRS = ["staticfiles"]

MEDIA_URL = "media/"
MEDIA_ROOT = "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DISCORD_WEBHOOK_URL = None

# Django social auth settings
SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "admin_panel.pipeline.configure_status",
)
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/"

SOCIAL_AUTH_DISCORD_KEY = settings.client_id
SOCIAL_AUTH_DISCORD_SECRET = settings.client_secret
SOCIAL_AUTH_DISCORD_SCOPE = ["identify", "guilds", "guilds.members.read"]

if settings.client_id and settings.client_secret:
    AUTHENTICATION_BACKENDS = [
        "social_core.backends.discord.DiscordOAuth2",
        "django.contrib.auth.backends.ModelBackend",
    ]
else:
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
    ]
