name: UV Lock Check

on:
  pull_request:
  push:

jobs:
  uv-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Verify lock is up to date
        run: |
          uv lock --frozen
      - name: Verify sync from lockfile
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv sync --frozen --no-install-project
